service: pokemon-serverless 

provider:
  name: aws
  runtime: nodejs8.10
  region: ${opt:region, 'eu-west-1'} 
  memorySize: 128

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: ${env:TABLE_ARN}

functions:
  getActivePokemon:
    handler: handler.getActivePokemon
    events:
      - http:
          path: pokemon/active
          method: get
          cors: true
    environment:
      TABLE_ARN: ${env:TABLE_ARN}
      S3URLPREFIX: ${env:S3URLPREFIX}

